# Generated by Django 2.1.5 on 2019-01-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
