# Generated by Django 2.1.5 on 2019-01-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MES', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
