# Generated by Django 2.1.5 on 2019-01-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MES', '0004_auto_20190118_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control_limit',
            fields=[
                ('size', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
